
export enum PlayerState {
PLAYING = 'PLAYING',
PAUSED = 'PAUSED',
STOPPED = 'STOPPED',
ENDED = 'ENDED',
LOADING = 'LOADING',
ERROR = 'ERROR',
IDLE = 'IDLE',
BUFFERING = 'BUFFERING'
}

export enum VolumeState {
MUTED = 'MUTED',
UNMUTED = 'UNMUTED'
}
